// src/routes/project.tsx
import { createFileRoute } from "@tanstack/react-router";
import { ChevronRight } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { WindowTitleBar } from "@/components/WindowTitleBar";
import { RetroButton } from "@/components/RetroButton";

export const Route = createFileRoute("/project")({
  head: () => ({
    meta: [
      { title: "Projects — Retro Mac Portfolio" },
      { name: "description", content: "Selected projects: SEO, content, and growth work shipped for real clients." },
      { property: "og:title", content: "Projects — Retro Mac Portfolio" },
      { property: "og:description", content: "Selected projects." },
    ],
  }),
  component: ProjectPage,
});

const projects = [
  {
    name: "Suzuki Indonesia Website", desc: "SEO Specialist - Successfully delivered 22,408,909 organic sessions.", stack: ["SEO", "Next.js", "Notion"]
  },
  { name: "Suzuki Indonesia Website Dealer", desc: "SEO Specialist - Successfully increased organic traffic on 49 of 50 dealer websites compared to the previous year.", stack: ["Strategy", "Copy", "Webflow"] },
  { name: "Mamasuka Website", desc: "SEO Specialist - Successfully increased the number of keywords in the Top 10 by 45.48% (from 1,284 to 1,868 keywords).", stack: ["Writing", "Ghost"] },
  { name: "BCA Life ", desc: "Blog Editor & Coordinator - Personal Project - Successfully helped improve the blog's organic performance through articles produced by +76.70%.", stack: ["Tech SEO", "Sheets"] },
  { name: "Kount", desc: "Web & SEO Writer - Personal Project - Outreach engine that placed 180+ contextual backlinks at DR 60+.", stack: ["Outreach", "Pitchbox"] },
  { name: "Ruangguru", desc: "Web & SEO Writer - Drove content strategy and topic ownership for the Skill Academy Blog, achieving 4 million clicks from 90 million impressions.", stack: ["Analytics", "Looker"] },
];

function ProjectPage() {
  return (
    <PageShell>
      <WindowTitleBar title="projects.sys">
        <div className="p-6 md:p-10">
          <h1 className="font-pixel text-2xl uppercase md:text-4xl">Selected Work</h1>
          <p className="mt-4 max-w-2xl font-mono-retro text-lg text-ink/80">
            A small archive of projects — each one a window into a different problem.
          </p>
        </div>
      </WindowTitleBar>

      <hr className="my-12 border-t-[2px] border-ink" />

      <section className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
        {projects.map((p) => (
          <WindowTitleBar key={p.name} title={p.name}>
            <div className="flex flex-col gap-4 p-4">
              <div
                className="aspect-[4/3] w-full border-[2px] border-ink"
                style={{
                  backgroundImage:
                    "repeating-linear-gradient(45deg, #1A1A1A 0 2px, transparent 2px 8px)",
                  backgroundColor: "#ECEFF3",
                }}
                aria-hidden
              />
              <p className="font-mono-retro text-base text-ink/85">{p.desc}</p>
              <ul className="flex flex-wrap gap-2">
                {p.stack.map((s) => (
                  <li key={s} className="border-[2px] border-ink px-2 py-1 font-mono-retro text-sm">
                    {s}
                  </li>
                ))}
              </ul>
              <RetroButton variant="primary" className="self-start">
                View Project <ChevronRight className="h-3.5 w-3.5" strokeWidth={3} />
              </RetroButton>
            </div>
          </WindowTitleBar>
        ))}
      </section>
    </PageShell>
  );
}

// pages/project.vue
<script setup lang="ts">
import { ChevronRight } from "lucide-vue-next";

// ── SEO ──────────────────────────────────────────────────────────────
useSeoMeta({
  title: "Projects — Gulman Azkiya | SEO Case Studies",
  description:
    "Selected SEO and content projects by Gulman Azkiya — including Suzuki Indonesia (22M organic sessions), BCA Life, Mamasuka, Ruangguru Skill Academy, and more.",
  ogTitle: "SEO Projects & Case Studies — Gulman Azkiya",
  ogDescription:
    "A portfolio of SEO and content work: 22M organic sessions for Suzuki, 45% keyword growth for Mamasuka, 4M clicks for Ruangguru Skill Academy.",
  ogUrl: "https://gulman.dev/project",
  ogImage: "https://gulman.dev/seo-specialist-gulman.jpg",
  twitterCard: "summary_large_image",
});

useHead({
  link: [{ rel: "canonical", href: "https://gulman.dev/project" }],
});

// ── Data ──────────────────────────────────────────────────────────────
const projects = [
  {
    name: "Suzuki Indonesia Website",
    desc: "SEO Specialist - Successfully delivered 22,408,909 organic sessions.",
    stack: ["SEO", "Next.js", "Notion"],
  },
  {
    name: "Suzuki Indonesia Website Dealer",
    desc: "SEO Specialist - Successfully increased organic traffic on 49 of 50 dealer websites compared to the previous year.",
    stack: ["Strategy", "Copy", "Webflow"],
  },
  {
    name: "Mamasuka Website",
    desc: "SEO Specialist - Successfully increased the number of keywords in the Top 10 by 45.48% (from 1,284 to 1,868 keywords).",
    stack: ["Writing", "Ghost"],
  },
  {
    name: "BCA Life",
    desc: "Blog Editor & Coordinator - Successfully helped improve the blog's organic performance through articles produced by +76.70%.",
    stack: ["Tech SEO", "Sheets"],
  },
  {
    name: "Kount",
    desc: "Web & SEO Writer - Outreach engine that placed 180+ contextual backlinks at DR 60+.",
    stack: ["Outreach", "Pitchbox"],
  },
  {
    name: "Ruangguru",
    desc: "Web & SEO Writer - Drove content strategy and topic ownership for the Skill Academy Blog, achieving 4 million clicks from 90 million impressions.",
    stack: ["Analytics", "Looker"],
  },
];
</script>

<template>
  <AppPageShell>
    <AppWindowTitleBar title="projects.sys">
      <div class="p-6 md:p-10">
        <h1 class="font-pixel text-2xl uppercase md:text-4xl">Selected Work</h1>
        <p class="mt-4 max-w-2xl font-mono-retro text-lg text-ink/80">
          A small archive of projects — each one a window into a different
          problem.
        </p>
      </div>
    </AppWindowTitleBar>

    <hr class="my-12 border-t-[2px] border-ink" />

    <!-- Projects grid -->
    <section
      class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3"
      aria-label="Project portfolio"
    >
      <AppWindowTitleBar
        v-for="project in projects"
        :key="project.name"
        :title="project.name"
      >
        <div class="flex flex-col gap-4 p-4">
          <!-- Placeholder pattern -->
          <div
            class="aspect-[4/3] w-full border-[2px] border-ink"
            style="
              background-image: repeating-linear-gradient(
                45deg,
                #1a1a1a 0 2px,
                transparent 2px 8px
              );
              background-color: #eceff3;
            "
            aria-hidden="true"
          />
          <p class="font-mono-retro text-base text-ink/85">{{ project.desc }}</p>
          <ul class="flex flex-wrap gap-2">
            <li
              v-for="tag in project.stack"
              :key="tag"
              class="border-[2px] border-ink px-2 py-1 font-mono-retro text-sm"
            >
              {{ tag }}
            </li>
          </ul>
          <AppRetroButton variant="primary" class="self-start">
            View Project
            <ChevronRight class="h-3.5 w-3.5" :stroke-width="3" />
          </AppRetroButton>
        </div>
      </AppWindowTitleBar>
    </section>
  </AppPageShell>
</template>
